import 'package:charades/src/bloc/game_bloc.dart';
import 'package:charades/src/models/category.dart';
import 'package:charades/src/screens/home_screen.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() {
  // Add your categories here!
  List<Category> initialCategories = [
    Category(
      name: "Animals",
      words: [
        "Dog",
        "Cat",
        "Elephant",
        "Lion",
        "Tiger",
        "Giraffe",
        "Zebra",
        "Monkey",
        "Bear",
        "Wolf",
        "Fox",
        "Rabbit",
        "Deer",
        "Horse",
        "Cow",
        "Pig",
        "Sheep",
        "Goat",
        "Chicken",
        "Duck",
        "Goose",
        "Turkey",
        "Penguin",
        "Eagle",
        "Hawk",
        "Owl",
        "Parrot",
        "Flamingo",
        "Peacock",
        "Swan",
        "Shark",
        "Dolphin",
        "Whale",
        "Octopus",
        "Squid",
        "Crab",
        "Lobster",
        "Jellyfish",
        "Seal",
        "Walrus",
        "Crocodile",
        "Alligator",
        "Snake",
        "Lizard",
        "Chameleon",
        "Turtle",
        "Tortoise",
        "Frog",
        "Toad",
        "Salamander",
        "Butterfly",
        "Bee",
        "Ant",
        "Spider",
        "Scorpion",
        "Grasshopper",
        "Dragonfly",
        "Beetle",
        "Ladybug",
        "Mosquito",
        "Camel",
        "Kangaroo",
        "Koala",
        "Panda",
        "Sloth",
        "Hedgehog",
        "Bat",
        "Raccoon",
        "Skunk",
        "Otter",
        "Weasel",
        "Ferret",
        "Mole",
        "Armadillo",
        "Platypus",
        "Wombat",
        "Lemur",
        "Meerkat",
        "Hyena",
        "Jackal",
        "Bison",
        "Buffalo",
        "Antelope",
        "Gazelle",
        "Moose",
        "Reindeer",
        "Donkey",
        "Mule",
        "Chimpanzee",
        "Gorilla",
        "Orangutan",
        "Leopard",
        "Cheetah",
        "Jaguar",
        "Panther",
        "Cougar",
        "Bobcat",
        "Lynx",
        "Badger",
        "Wolverine",
        "Alpaca",
        "Llama",
        "Yak",
        "Boar",
        "Opossum",
        "Tasmanian Devil",
        "Dingo",
        "Kiwi",
        "Cassowary",
        "Emu",
        "Pelican",
        "Seagull",
        "Woodpecker",
        "Canary",
        "Finch",
        "Sparrow",
        "Robin",
        "Crow",
        "Raven",
        "Magpie",
        "Swordfish",
        "Tuna",
        "Salmon",
        "Trout",
        "Piranha",
        "Clownfish",
        "Seahorse",
        "Starfish",
        "Manta Ray",
        "Stingray",
        "Electric Eel",
        "Komodo Dragon",
        "Axolotl",
        "Narwhal",
        "Beluga Whale",
        "Blue Whale",
        "Humpback Whale",
        "Orca",
        "Manatee",
        "Dugong",
      ],
    ),
    Category(
      name: "Movies",
      words: [
        "Inception",
        "The Matrix",
        "Titanic",
        "The Godfather",
        "Pulp Fiction",
        "The Dark Knight",
        "Forrest Gump",
        "Gladiator",
        "Jurassic Park",
        "Avatar",
        "Avengers: Endgame",
        "Avengers: Infinity War",
        "Iron Man",
        "Black Panther",
        "Spider-Man: No Way Home",
        "The Batman",
        "Joker",
        "Deadpool",
        "Logan",
        "Doctor Strange",
        "Interstellar",
        "Dune",
        "Oppenheimer",
        "Tenet",
        "The Prestige",
        "The Shawshank Redemption",
        "Fight Club",
        "Se7en",
        "Gone Girl",
        "The Social Network",
        "La La Land",
        "Whiplash",
        "The Greatest Showman",
        "A Star Is Born",
        "Bohemian Rhapsody",
        "Frozen",
        "Frozen II",
        "Encanto",
        "Moana",
        "Coco",
        "Toy Story",
        "Toy Story 3",
        "Toy Story 4",
        "Finding Nemo",
        "Finding Dory",
        "Inside Out",
        "Up",
        "Soul",
        "Luca",
        "Turning Red",
        "Shrek",
        "Shrek 2",
        "Kung Fu Panda",
        "How to Train Your Dragon",
        "Despicable Me",
        "Minions",
        "The Incredibles",
        "Incredibles 2",
        "Ratatouille",
        "WALL-E",
        "Harry Potter and the Sorcerer’s Stone",
        "Harry Potter and the Deathly Hallows",
        "Fantastic Beasts",
        "The Lord of the Rings: The Fellowship of the Ring",
        "The Two Towers",
        "The Return of the King",
        "The Hobbit",
        "Pirates of the Caribbean",
        "The Curse of the Black Pearl",
        "Dead Man’s Chest",
        "No Time to Die",
        "Skyfall",
        "Casino Royale",
        "Mission: Impossible",
        "Top Gun",
        "Top Gun: Maverick",
        "Fast & Furious",
        "Fast Five",
        "Furious 7",
        "John Wick",
        "John Wick: Chapter 2",
        "John Wick: Chapter 3",
        "Mad Max: Fury Road",
        "The Hunger Games",
        "Catching Fire",
        "The Maze Runner",
        "Divergent",
        "Twilight",
        "The Fault in Our Stars",
        "Me Before You",
        "Barbie",
        "The Super Mario Bros. Movie",
        "Wonka",
        "Elemental",
        "Wish",
        "Get Out",
        "Us",
        "Nope",
        "A Quiet Place",
        "A Quiet Place Part II",
        "The Conjuring",
        "The Nun",
        "It",
        "It Chapter Two",
        "Hereditary",
        "Midsommar",
        "The Babadook",
        "Smile",
        "The Invisible Man",
        "Talk to Me",
        "Knives Out",
        "Glass Onion",
        "Murder on the Orient Express",
        "Death on the Nile",
        "Sherlock Holmes",
        "The Grand Budapest Hotel",
        "Parasite",
        "Everything Everywhere All at Once",
        "The Menu",
        "Triangle of Sadness",
        "The Wolf of Wall Street",
        "Catch Me If You Can",
        "The Big Short",
        "Moneyball",
        "Steve Jobs",
        "1917",
        "Dunkirk",
        "Saving Private Ryan",
        "Hacksaw Ridge",
        "All Quiet on the Western Front",
        "The Revenant",
        "Life of Pi",
        "Gravity",
        "Cast Away",
        "The Martian",
        "Edge of Tomorrow",
        "Ready Player One",
        "Blade Runner 2049",
        "Ex Machina",
        "Her",
      ],
    ),
    Category(
      name: "TV Shows",
      words: [
        "Breaking Bad",
        "Better Call Saul",
        "Game of Thrones",
        "House of the Dragon",
        "The Sopranos",
        "The Wire",
        "Stranger Things",
        "The Walking Dead",
        "The Last of Us",
        "Westworld",
        "Dark",
        "Black Mirror",
        "Severance",
        "Lost",
        "Prison Break",
        "Narcos",
        "Ozark",
        "Peaky Blinders",
        "Boardwalk Empire",
        "Mindhunter",
        "True Detective",
        "Fargo",
        "Dexter",
        "Dexter: New Blood",
        "Hannibal",
        "The Office",
        "Parks and Recreation",
        "Brooklyn Nine-Nine",
        "Friends",
        "How I Met Your Mother",
        "The Big Bang Theory",
        "Modern Family",
        "New Girl",
        "Arrested Development",
        "Community",
        "Ted Lasso",
        "The Bear",
        "Only Murders in the Building",
        "Barry",
        "Fleabag",
        "Euphoria",
        "Sex Education",
        "13 Reasons Why",
        "Skins",
        "Gossip Girl",
        "The Crown",
        "Bridgerton",
        "Downton Abbey",
        "Mad Men",
        "The Americans",
        "Vikings",
        "The Witcher",
        "Shadow and Bone",
        "Outlander",
        "Rome",
        "The Mandalorian",
        "Andor",
        "Obi-Wan Kenobi",
        "Loki",
        "WandaVision",
        "The Falcon and the Winter Soldier",
        "Hawkeye",
        "Moon Knight",
        "Daredevil",
        "Jessica Jones",
        "The Boys",
        "Gen V",
        "Invincible",
        "The Umbrella Academy",
        "Titans",
        "Avatar: The Last Airbender",
        "The Legend of Korra",
        "Rick and Morty",
        "BoJack Horseman",
        "Family Guy",
        "The Simpsons",
        "South Park",
        "Futurama",
        "Adventure Time",
        "Regular Show",
        "SpongeBob SquarePants",
        "Gravity Falls",
        "Steven Universe",
        "Arcane",
        "Bluey",
        "Chernobyl",
        "Band of Brothers",
        "The Pacific",
        "When They See Us",
        "Dahmer",
        "Squid Game",
        "Alice in Borderland",
        "Money Heist",
        "Lupin",
        "Elite",
        "Wednesday",
        "The Addams Family",
        "American Horror Story",
        "The Haunting of Hill House",
        "Midnight Mass",
        "Love Island",
        "Too Hot to Handle",
        "The Circle",
        "Survivor",
        "Big Brother",
        "MasterChef",
        "Hell’s Kitchen",
        "The Great British Bake Off",
        "Top Chef",
        "Kitchen Nightmares",
        "Planet Earth",
        "Blue Planet",
        "Cosmos",
        "Our Planet",
        "My Octopus Teacher",
        "MythBusters",
        "Shark Tank",
        "Dragon’s Den",
        "Undercover Boss",
        "Queer Eye",
        "Doctor Who",
        "Sherlock",
        "Blackadder",
        "Mr. Bean",
        "The IT Crowd",
        "Line of Duty",
        "Bodyguard",
        "Broadchurch",
        "Happy Valley",
        "Killing Eve",
        "NCIS",
        "CSI",
        "Grey’s Anatomy",
        "House",
        "ER",
        "Scrubs",
        "The Good Doctor",
        "Chicago Fire",
        "Chicago P.D.",
        "Law & Order",
        "Suits",
        "Billions",
        "Succession",
        "Industry",
        "The Newsroom",
        "Silicon Valley",
        "Halt and Catch Fire",
        "Mr. Robot",
        "Scandal",
        "House of Cards",
      ],
    ),
    Category(
      name: "Fictional Characters",
      words: [
        "Harry Potter",
        "Hermione Granger",
        "Ron Weasley",
        "Albus Dumbledore",
        "Lord Voldemort",
        "Frodo Baggins",
        "Gandalf",
        "Aragorn",
        "Legolas",
        "Gollum",
        "Luke Skywalker",
        "Darth Vader",
        "Princess Leia",
        "Han Solo",
        "Yoda",
        "Spider-Man",
        "Iron Man",
        "Captain America",
        "Thor",
        "Hulk",
        "Black Widow",
        "Doctor Strange",
        "Black Panther",
        "Scarlet Witch",
        "Loki",
        "Batman",
        "Superman",
        "Wonder Woman",
        "Joker",
        "Harley Quinn",
        "Flash",
        "Aquaman",
        "Green Lantern",
        "Catwoman",
        "Lex Luthor",
        "Sherlock Holmes",
        "Dr. Watson",
        "James Bond",
        "Indiana Jones",
        "Jack Sparrow",
        "Rocky Balboa",
        "John Wick",
        "Ethan Hunt",
        "Jason Bourne",
        "Maximus",
        "Walter White",
        "Jesse Pinkman",
        "Saul Goodman",
        "Tony Soprano",
        "Michael Scott",
        "Dwight Schrute",
        "Jim Halpert",
        "Pam Beesly",
        "Homer Simpson",
        "Bart Simpson",
        "Lisa Simpson",
        "Marge Simpson",
        "Peter Griffin",
        "Stewie Griffin",
        "Rick Sanchez",
        "Morty Smith",
        "BoJack Horseman",
        "SpongeBob SquarePants",
        "Patrick Star",
        "Squidward",
        "Shrek",
        "Donkey",
        "Puss in Boots",
        "Po",
        "Kung Fu Panda",
        "Hiccup",
        "Toothless",
        "Elsa",
        "Anna",
        "Olaf",
        "Simba",
        "Mufasa",
        "Scar",
        "Aladdin",
        "Genie",
        "Woody",
        "Buzz Lightyear",
        "Lightning McQueen",
        "Mater",
        "Remy",
        "WALL-E",
        "EVE",
        "Joy",
        "Sadness",
        "Miguel",
        "Geralt of Rivia",
        "Ciri",
        "Yennefer",
        "Kratos",
        "Atreus",
        "Master Chief",
        "Cortana",
        "Link",
        "Zelda",
        "Ganondorf",
        "Mario",
        "Luigi",
        "Princess Peach",
        "Bowser",
        "Donkey Kong",
        "Pikachu",
        "Ash Ketchum",
        "Charizard",
        "Mewtwo",
        "Jigglypuff",
        "Lara Croft",
        "Nathan Drake",
        "Joel Miller",
        "Ellie Williams",
        "Arthur Morgan",
        "Trevor Philips",
        "Franklin Clinton",
        "Niko Bellic",
        "Agent 47",
        "Solid Snake",
        "Cloud Strife",
        "Sephiroth",
        "Tifa Lockhart",
        "Aerith Gainsborough",
        "Noctis",
        "Sonic the Hedgehog",
        "Shadow the Hedgehog",
        "Knuckles",
        "Tails",
        "Crash Bandicoot",
        "Spyro",
        "Ratchet",
        "Clank",
        "Jak",
        "Daxter",
        "Aang",
        "Katara",
        "Sokka",
        "Zuko",
        "Toph",
        "Korra",
        "Asami",
        "Tanjiro Kamado",
        "Nezuko Kamado",
        "Goku",
        "Vegeta",
        "Naruto Uzumaki",
        "Sasuke Uchiha",
        "Monkey D. Luffy",
        "Roronoa Zoro",
      ],
    ),
    Category(
      name: "Celebrities",
      words: [
        "Taylor Swift",
        "Drake",
        "Beyoncé",
        "Rihanna",
        "Ariana Grande",
        "Billie Eilish",
        "The Weeknd",
        "Ed Sheeran",
        "Justin Bieber",
        "Lady Gaga",
        "Kanye West",
        "Dua Lipa",
        "Harry Styles",
        "Olivia Rodrigo",
        "Bruno Mars",
        "Kendrick Lamar",
        "Travis Scott",
        "Post Malone",
        "Doja Cat",
        "SZA",
        "Leonardo DiCaprio",
        "Brad Pitt",
        "Angelina Jolie",
        "Tom Cruise",
        "Scarlett Johansson",
        "Robert Downey Jr.",
        "Chris Hemsworth",
        "Chris Evans",
        "Zendaya",
        "Timothée Chalamet",
        "Jennifer Lawrence",
        "Emma Stone",
        "Margot Robbie",
        "Ryan Gosling",
        "Ryan Reynolds",
        "Dwayne Johnson",
        "Jason Momoa",
        "Keanu Reeves",
        "Johnny Depp",
        "Will Smith",
        "Denzel Washington",
        "Morgan Freeman",
        "Tom Hanks",
        "Meryl Streep",
        "Julia Roberts",
        "Anne Hathaway",
        "Natalie Portman",
        "Gal Gadot",
        "Millie Bobby Brown",
        "Jenna Ortega",
        "Pedro Pascal",
        "Oscar Isaac",
        "Cillian Murphy",
        "Florence Pugh",
        "Anya Taylor-Joy",
        "Hugh Jackman",
        "Christian Bale",
        "Matt Damon",
        "Ben Affleck",
        "Mark Wahlberg",
        "Selena Gomez",
        "Miley Cyrus",
        "Demi Lovato",
        "Shawn Mendes",
        "Camila Cabello",
        "Kim Kardashian",
        "Kylie Jenner",
        "Kendall Jenner",
        "Khloé Kardashian",
        "Kourtney Kardashian",
        "Oprah Winfrey",
        "Ellen DeGeneres",
        "Jimmy Fallon",
        "Stephen Colbert",
        "Trevor Noah",
        "Gordon Ramsay",
        "Jamie Oliver",
        "MrBeast",
        "PewDiePie",
        "Markiplier",
        "Charli D’Amelio",
        "Addison Rae",
        "Logan Paul",
        "Jake Paul",
        "David Dobrik",
        "Cristiano Ronaldo",
        "Lionel Messi",
        "Neymar Jr.",
        "Kylian Mbappé",
        "LeBron James",
        "Michael Jordan",
        "Serena Williams",
        "Roger Federer",
        "Rafael Nadal",
        "Novak Djokovic",
        "Elon Musk",
        "Jeff Bezos",
        "Bill Gates",
        "Mark Zuckerberg",
        "Steve Jobs",
      ],
    ),
    Category(
      name: "Music",
      words: [
        "Blinding Lights",
        "Shape of You",
        "Uptown Funk",
        "Happy",
        "Shake It Off",
        "Bad Guy",
        "Levitating",
        "As It Was",
        "Watermelon Sugar",
        "Someone Like You",
        "Halo",
        "Single Ladies",
        "Umbrella",
        "Diamonds",
        "Old Town Road",
        "Sunflower",
        "Circles",
        "Rockstar",
        "Sicko Mode",
        "HUMBLE.",
        "All the Stars",
        "God’s Plan",
        "Hotline Bling",
        "One Dance",
        "Closer",
        "Stay",
        "Senorita",
        "Peaches",
        "Sorry",
        "Take on Me",
        "Billie Jean",
        "Thriller",
        "Like a Prayer",
        "Sweet Child O’ Mine",
        "Smells Like Teen Spirit",
        "Wonderwall",
        "Bohemian Rhapsody",
        "Don’t Stop Me Now",
        "Imagine",
        "Hey Jude",
        "Let It Be",
        "Hotel California",
        "Stairway to Heaven",
        "Yesterday",
        "I Will Always Love You",
        "My Heart Will Go On",
        "Rolling in the Deep",
        "Firework",
        "Roar",
        "Bad Romance",
        "Poker Face",
        "Born This Way",
        "Just Dance",
        "Telephone",
        "Havana",
        "Girls Like You",
        "Shallow",
        "Easy On Me",
        "Ghost",
        "Thank U, Next",
        "7 Rings",
        "Break My Heart",
        "Positions",
        "Dynamite",
        "Butter",
        "Permission to Dance",
        "Boy With Luv",
        "Blood Sweat & Tears",
        "Gangnam Style",
        "Gentleman",
        "Ddu-Du Ddu-Du",
        "Kill This Love",
        "How You Like That",
        "Numb",
        "In the End",
        "Crawling",
        "Somewhere I Belong",
        "Breaking the Habit",
        "Enter Sandman",
        "Nothing Else Matters",
        "The Unforgiven",
        "Fade to Black",
        "One",
        "Back in Black",
        "Thunderstruck",
        "Highway to Hell",
        "You Shook Me All Night Long",
        "Hells Bells",
        "Sweet Home Alabama",
        "Free Bird",
        "Simple Man",
        "Knockin' on Heaven’s Door",
        "Bad Moon Rising",
        "Livin’ on a Prayer",
        "You Give Love a Bad Name",
        "Wanted Dead or Alive",
        "Run to You",
        "It’s My Life",
      ],
    ),
    Category(
      name: "Food",
      words: [
        "Pizza",
        "Burger",
        "Hot Dog",
        "French Fries",
        "Fried Chicken",
        "Spaghetti",
        "Lasagna",
        "Mac and Cheese",
        "Tacos",
        "Burrito",
        "Quesadilla",
        "Nachos",
        "Enchiladas",
        "Chili",
        "Steak",
        "Ribs",
        "Meatballs",
        "Roast Chicken",
        "Fajitas",
        "Paella",
        "Sushi",
        "Ramen",
        "Udon",
        "Soba",
        "Tempura",
        "Sashimi",
        "Miso Soup",
        "Onigiri",
        "Gyoza",
        "Takoyaki",
        "Curry",
        "Butter Chicken",
        "Tikka Masala",
        "Biryani",
        "Naan",
        "Samosa",
        "Pakora",
        "Dal",
        "Chole",
        "Rogan Josh",
        "Pho",
        "Banh Mi",
        "Spring Rolls",
        "Pad Thai",
        "Green Curry",
        "Red Curry",
        "Tom Yum",
        "Fried Rice",
        "Dim Sum",
        "Lo Mein",
        "Bao",
        "Congee",
        "Kimchi",
        "Bibimbap",
        "Bulgogi",
        "Hot Pot",
        "Dumplings",
        "Pierogi",
        "Borscht",
        "Blini",
        "Pancakes",
        "Waffles",
        "Crepes",
        "French Toast",
        "Bagel",
        "Croissant",
        "Donut",
        "Muffin",
        "Brownie",
        "Cupcake",
        "Cheesecake",
        "Ice Cream",
        "Gelato",
        "Sorbet",
        "Pudding",
        "Apple Pie",
        "Pumpkin Pie",
        "Chocolate Cake",
        "Carrot Cake",
        "Tiramisu",
        "Baklava",
        "Macaron",
        "Eclair",
        "Churros",
        "Cannoli",
        "Popcorn",
        "Pretzel",
        "Trail Mix",
        "Granola Bar",
        "Nachos with Cheese",
        "Guacamole",
        "Hummus",
        "Falafel",
        "Shawarma",
        "Gyro",
        "Ceviche",
        "Fish and Chips",
        "Clam Chowder",
        "Lobster Roll",
        "Crab Cakes",
        "Oysters",
        "Scallops",
        "Shrimp Cocktail",
        "Calamari",
        "Mussels",
      ],
    ),
    Category(
      name: "Drinks",
      words: [
        "Water",
        "Orange Juice",
        "Apple Juice",
        "Grape Juice",
        "Pineapple Juice",
        "Cranberry Juice",
        "Tomato Juice",
        "Lemonade",
        "Iced Tea",
        "Green Tea",
        "Black Tea",
        "Herbal Tea",
        "Chai Tea",
        "Coffee",
        "Espresso",
        "Cappuccino",
        "Latte",
        "Mocha",
        "Macchiato",
        "Americano",
        "Hot Chocolate",
        "Milkshake",
        "Smoothie",
        "Protein Shake",
        "Kombucha",
        "Soda",
        "Cola",
        "Diet Cola",
        "Root Beer",
        "Ginger Ale",
        "Tonic Water",
        "Club Soda",
        "Sparkling Water",
        "Energy Drink",
        "Sports Drink",
        "Beer",
        "Lager",
        "Ale",
        "Stout",
        "Pilsner",
        "IPA",
        "Wheat Beer",
        "Cider",
        "Hard Cider",
        "Mead",
        "Wine",
        "Red Wine",
        "White Wine",
        "Rosé",
        "Champagne",
        "Prosecco",
        "Sparkling Wine",
        "Sherry",
        "Port",
        "Vermouth",
        "Whiskey",
        "Bourbon",
        "Scotch",
        "Rye Whiskey",
        "Irish Whiskey",
        "Vodka",
        "Gin",
        "Rum",
        "Tequila",
        "Brandy",
        "Cognac",
        "Absinthe",
        "Sake",
        "Baijiu",
        "Soju",
        "Cocktail",
        "Margarita",
        "Martini",
        "Mojito",
        "Daiquiri",
        "Pina Colada",
        "Bloody Mary",
        "Cosmopolitan",
        "Old Fashioned",
        "Negroni",
        "Mai Tai",
        "Long Island Iced Tea",
        "Manhattan",
        "Whiskey Sour",
        "Tom Collins",
        "Mint Julep",
        "Caipirinha",
        "Sangria",
        "Bellini",
        "Aperol Spritz",
        "Hot Toddy",
        "Mulled Wine",
        "Irish Coffee",
        "Eggnog",
        "Chai Latte",
      ],
    ),
    Category(
      name: "Jobs",
      words: [
        "Doctor",
        "Nurse",
        "Surgeon",
        "Dentist",
        "Pharmacist",
        "Veterinarian",
        "Therapist",
        "Psychologist",
        "Physiotherapist",
        "Optometrist",
        "Teacher",
        "Professor",
        "Tutor",
        "Coach",
        "Principal",
        "Chef",
        "Baker",
        "Pastry Chef",
        "Barista",
        "Sous Chef",
        "Waiter",
        "Waitress",
        "Bartender",
        "Sommelier",
        "Host",
        "Engineer",
        "Software Engineer",
        "Civil Engineer",
        "Mechanical Engineer",
        "Electrical Engineer",
        "Architect",
        "Interior Designer",
        "Urban Planner",
        "Graphic Designer",
        "UX Designer",
        "Pilot",
        "Flight Attendant",
        "Air Traffic Controller",
        "Astronaut",
        "Test Pilot",
        "Police Officer",
        "Detective",
        "Sheriff",
        "Security Guard",
        "FBI Agent",
        "Firefighter",
        "Paramedic",
        "EMT",
        "Lifeguard",
        "Rescue Worker",
        "Farmer",
        "Rancher",
        "Fisherman",
        "Agronomist",
        "Horticulturist",
        "Writer",
        "Journalist",
        "Author",
        "Editor",
        "Blogger",
        "Actor",
        "Actress",
        "Comedian",
        "Director",
        "Producer",
        "Musician",
        "Singer",
        "DJ",
        "Composer",
        "Songwriter",
        "Athlete",
        "Coach",
        "Referee",
        "Personal Trainer",
        "Yoga Instructor",
        "Lawyer",
        "Judge",
        "Paralegal",
        "Legal Assistant",
        "Mediator",
        "Politician",
        "Mayor",
        "Senator",
        "Governor",
        "President",
        "Entrepreneur",
        "CEO",
        "Manager",
        "Consultant",
        "Investor",
        "Scientist",
        "Biologist",
        "Chemist",
        "Physicist",
        "Researcher",
        "Artist",
        "Painter",
        "Sculptor",
        "Illustrator",
        "Animator",
        "Mechanic",
        "Plumber",
        "Electrician",
        "Carpenter",
        "Welder",
      ],
    ),
    Category(
      name: "Sports & Activities",
      words: [
        "Football",
        "Basketball",
        "Tennis",
        "Swimming",
        "Running",
        "Cycling",
        "Baseball",
        "Volleyball",
        "Golf",
        "Boxing",
        "Surfing",
        "Skiing",
        "Snowboarding",
        "Skateboarding",
        "Yoga",
        "Hiking",
        "Climbing",
        "Fishing",
        "Bowling",
        "Dancing",
        "Jump Rope",
        "Martial Arts",
        "Ice Skating",
        "Horse Riding",
        "Rowing",
        "Archery",
        "Gymnastics",
        "Weightlifting",
        "Badminton",
        "Table Tennis",
        "Rugby",
        "Cricket",
        "Handball",
        "Water Polo",
        "Dodgeball",
        "Kickboxing",
        "Karate",
        "Judo",
        "Taekwondo",
        "Fencing",
        "Wrestling",
        "Parkour",
        "Pilates",
        "Zumba",
        "Aerobics",
        "CrossFit",
        "Bodybuilding",
        "Jogging",
        "Trail Running",
        "Mountain Biking",
        "BMX",
        "Scootering",
        "Rollerblading",
        "Ice Hockey",
        "Field Hockey",
        "Lacrosse",
        "Softball",
        "Frisbee",
        "Ultimate Frisbee",
        "Disc Golf",
        "Ping Pong",
        "Snooker",
        "Pool",
        "Darts",
        "Chess",
        "Checkers",
        "E-sports",
        "Gaming",
        "VR Gaming",
        "Meditation",
        "Stretching",
        "Camping",
        "Backpacking",
        "Orienteering",
        "Geocaching",
        "Bird Watching",
        "Kayaking",
        "Canoeing",
        "Sailing",
        "Windsurfing",
        "Kitesurfing",
        "Scuba Diving",
        "Snorkeling",
        "Free Diving",
        "Rock Climbing",
        "Bouldering",
        "Abseiling",
        "Ziplining",
        "Trampolining",
        "Cheerleading",
        "Marching",
        "Drumming",
        "Singing",
        "Acting",
        "Painting",
        "Drawing",
        "Photography",
      ],
    ),
    Category(
      name: "Video Games",
      words: [
        "Minecraft",
        "Fortnite",
        "Call of Duty",
        "Grand Theft Auto",
        "The Legend of Zelda",
        "Super Mario Bros",
        "FIFA",
        "League of Legends",
        "Overwatch",
        "Apex Legends",
        "Valorant",
        "Counter-Strike",
        "Dota 2",
        "Rocket League",
        "PUBG",
        "Roblox",
        "Among Us",
        "The Sims",
        "Animal Crossing",
        "Pokémon",
        "Elden Ring",
        "Dark Souls",
        "Bloodborne",
        "Sekiro",
        "God of War",
        "Uncharted",
        "The Last of Us",
        "Horizon Zero Dawn",
        "Ghost of Tsushima",
        "Red Dead Redemption",
        "Cyberpunk 2077",
        "Assassin’s Creed",
        "Far Cry",
        "Watch Dogs",
        "Battlefield",
        "Halo",
        "Gears of War",
        "Destiny",
        "Warframe",
        "Monster Hunter",
        "Final Fantasy",
        "Kingdom Hearts",
        "Persona 5",
        "Dragon Quest",
        "Resident Evil",
        "Silent Hill",
        "Dead by Daylight",
        "Five Nights at Freddy’s",
        "Outlast",
        "Amnesia",
        "Cuphead",
        "Hollow Knight",
        "Celeste",
        "Ori and the Blind Forest",
        "Stardew Valley",
        "Terraria",
        "Subnautica",
        "No Man’s Sky",
        "Fall Guys",
        "Crash Bandicoot",
        "Spyro the Dragon",
        "Rayman",
        "Banjo-Kazooie",
        "Donkey Kong",
        "Metroid",
        "Castlevania",
        "Street Fighter",
        "Mortal Kombat",
        "Tekken",
        "Super Smash Bros",
        "NBA 2K",
        "Madden NFL",
        "Need for Speed",
        "Gran Turismo",
        "Forza Horizon",
        "Mario Kart",
        "Plants vs Zombies",
        "Clash of Clans",
        "Clash Royale",
        "Brawl Stars",
        "Angry Birds",
        "Temple Run",
        "Candy Crush",
        "Geometry Dash",
        "Jetpack Joyride",
        "Crossy Road",
        "Flappy Bird",
        "Slither.io",
        "Agar.io",
        "Zelda: Breath of the Wild",
        "Tetris",
        "Pac-Man",
        "Space Invaders",
        "Pong",
      ],
    ),
    Category(
      name: "Books & Authors",
      words: [
        "Harry Potter",
        "The Lord of the Rings",
        "The Hobbit",
        "Game of Thrones",
        "A Clash of Kings",
        "A Storm of Swords",
        "A Feast for Crows",
        "A Dance with Dragons",
        "The Hunger Games",
        "Catching Fire",
        "Mockingjay",
        "Twilight",
        "New Moon",
        "Eclipse",
        "Breaking Dawn",
        "The Great Gatsby",
        "To Kill a Mockingbird",
        "1984",
        "Animal Farm",
        "Brave New World",
        "Fahrenheit 451",
        "The Catcher in the Rye",
        "Moby Dick",
        "War and Peace",
        "Crime and Punishment",
        "Pride and Prejudice",
        "Sense and Sensibility",
        "Emma",
        "Jane Eyre",
        "Wuthering Heights",
        "Dracula",
        "Frankenstein",
        "The Picture of Dorian Gray",
        "Les Misérables",
        "The Count of Monte Cristo",
        "Don Quixote",
        "The Alchemist",
        "The Little Prince",
        "The Da Vinci Code",
        "Angels and Demons",
        "Inferno",
        "The Girl with the Dragon Tattoo",
        "The Girl Who Played with Fire",
        "The Girl Who Kicked the Hornets’ Nest",
        "The Shining",
        "It",
        "Carrie",
        "Misery",
        "Pet Sematary",
        "The Stand",
        "The Fault in Our Stars",
        "Looking for Alaska",
        "Paper Towns",
        "The Book Thief",
        "The Kite Runner",
        "A Thousand Splendid Suns",
        "Life of Pi",
        "The Chronicles of Narnia",
        "The Lion the Witch and the Wardrobe",
        "Prince Caspian",
        "The Voyage of the Dawn Treader",
        "The Silver Chair",
        "The Last Battle",
        "The Magician’s Nephew",
        "The Horse and His Boy",
        "Percy Jackson",
        "The Lightning Thief",
        "The Sea of Monsters",
        "The Titan’s Curse",
        "The Battle of the Labyrinth",
        "The Last Olympian",
        "The Maze Runner",
        "The Scorch Trials",
        "The Death Cure",
        "Divergent",
        "Insurgent",
        "Allegiant",
        "Ready Player One",
        "Ender’s Game",
        "Dune",
        "Foundation",
        "I Robot",
        "The Handmaid’s Tale",
        "The Road",
        "No Country for Old Men",
        "The Girl on the Train",
        "Gone Girl",
        "Big Little Lies",
        "The Silent Patient",
        "Where the Crawdads Sing",
        "Normal People",
        "Call Me by Your Name",
        "The Perks of Being a Wallflower",
        "The Outsiders",
        "Of Mice and Men",
        "The Grapes of Wrath",
        "East of Eden",
        "Slaughterhouse Five",
        "Catch-22",
        "The Bell Jar",
        "Rebecca",
        "Lolita",
        "The Secret Garden",
        "Anne of Green Gables",
        "Little Women",
        "Heidi",
        "Black Beauty",
        "Treasure Island",
        "Robinson Crusoe",
        "Gulliver’s Travels",
        "The Time Machine",
        "The War of the Worlds",
        "The Invisible Man",
        "The Hound of the Baskervilles",
        "A Study in Scarlet",
        "The Adventures of Sherlock Holmes",
        "The Fellowship of the Ring",
        "The Two Towers",
        "The Return of the King",
        "Eragon",
        "Eldest",
        "Brisingr",
        "Inheritance",
        "The Name of the Wind",
        "The Wise Man’s Fear",
        "Mistborn",
        "The Final Empire",
        "The Well of Ascension",
        "The Hero of Ages",
        "The Way of Kings",
        "Words of Radiance",
        "Oathbringer",
        "Rhythm of War",
        "The Color Purple",
        "Beloved",
        "Invisible Man",
        "Things Fall Apart",
        "Half of a Yellow Sun",
        "Americanah",
      ],
    ),
    Category(
      name: "Superheroes & Villains",
      words: [
        "Superman",
        "Batman",
        "Wonder Woman",
        "Spider-Man",
        "Iron Man",
        "Captain America",
        "Thor",
        "Hulk",
        "Black Widow",
        "Hawkeye",
        "Doctor Strange",
        "Scarlet Witch",
        "Vision",
        "Falcon",
        "Winter Soldier",
        "Black Panther",
        "Ant-Man",
        "Wasp",
        "Captain Marvel",
        "Star-Lord",
        "Gamora",
        "Drax",
        "Rocket Raccoon",
        "Groot",
        "Deadpool",
        "Wolverine",
        "Professor X",
        "Magneto",
        "Mystique",
        "Cyclops",
        "Storm",
        "Jean Grey",
        "Nightcrawler",
        "Beast",
        "Rogue",
        "Gambit",
        "Green Lantern",
        "Flash",
        "Aquaman",
        "Cyborg",
        "Green Arrow",
        "Shazam",
        "Supergirl",
        "Batgirl",
        "Robin",
        "Nightwing",
        "Red Hood",
        "Catwoman",
        "Joker",
        "Harley Quinn",
        "Poison Ivy",
        "Penguin",
        "Riddler",
        "Two-Face",
        "Bane",
        "Scarecrow",
        "Lex Luthor",
        "Darkseid",
        "Thanos",
        "Loki",
        "Ultron",
        "Red Skull",
        "Killmonger",
        "Hela",
        "Venom",
        "Carnage",
        "Green Goblin",
        "Doctor Octopus",
        "Sandman",
        "Electro",
        "Lizard",
        "Vulture",
        "Kingpin",
        "Daredevil",
        "Punisher",
        "Jessica Jones",
        "Luke Cage",
        "Iron Fist",
        "Moon Knight",
        "She-Hulk",
        "Ms Marvel",
        "Nova",
        "Silver Surfer",
        "Ghost Rider",
        "Blade",
        "Elektra",
        "Shang-Chi",
        "Kang the Conqueror",
        "Apocalypse",
        "Galactus",
        "Doctor Doom",
        "Black Adam",
        "Reverse Flash",
        "Sinestro",
        "Brainiac",
      ],
    ),
    Category(
      name: "Cartoon Characters",
      words: [
        "Mickey Mouse",
        "Minnie Mouse",
        "Donald Duck",
        "Goofy",
        "Pluto",
        "Scooby-Doo",
        "Shaggy",
        "Fred Flintstone",
        "Barney Rubble",
        "Bugs Bunny",
        "Daffy Duck",
        "Porky Pig",
        "Tweety",
        "Sylvester",
        "Road Runner",
        "Wile E. Coyote",
        "Tom",
        "Jerry",
        "Popeye",
        "Olive Oyl",
        "Woody Woodpecker",
        "Pink Panther",
        "Garfield",
        "Odie",
        "Snoopy",
        "Charlie Brown",
        "Lucy",
        "Linus",
        "Dexter",
        "Dee Dee",
        "Johnny Bravo",
        "Samurai Jack",
        "Powerpuff Girls",
        "Blossom",
        "Bubbles",
        "Buttercup",
        "Ben 10",
        "Gwen",
        "Kevin Levin",
        "Kim Possible",
        "Ron Stoppable",
        "Phineas",
        "Ferb",
        "Candace",
        "Perry the Platypus",
        "Dr Doofenshmirtz",
        "SpongeBob SquarePants",
        "Patrick Star",
        "Squidward",
        "Mr Krabs",
        "Plankton",
        "Sandy Cheeks",
        "Timmy Turner",
        "Cosmo",
        "Wanda",
        "Danny Phantom",
        "Jimmy Neutron",
        "Courage the Cowardly Dog",
        "Ed",
        "Edd",
        "Eddy",
        "Samurai Jack",
        "Ash Ketchum",
        "Pikachu",
        "Misty",
        "Brock",
        "Goku",
        "Vegeta",
        "Naruto",
        "Sasuke",
        "Luffy",
        "Zoro",
        "Nami",
        "Usopp",
        "Sanji",
        "Shrek",
        "Donkey",
        "Fiona",
        "Puss in Boots",
        "Homer Simpson",
        "Marge Simpson",
        "Bart Simpson",
        "Lisa Simpson",
        "Maggie Simpson",
        "Peter Griffin",
        "Stewie Griffin",
        "Brian Griffin",
        "Lois Griffin",
        "Meg Griffin",
        "Rick Sanchez",
        "Morty Smith",
        "Finn",
        "Jake the Dog",
        "Steven Universe",
        "Garnet",
        "Amethyst",
        "Pearl",
      ],
    ),
  ];

  runApp(
    BlocProvider(
      create: (context) => GameBloc(initialCategories),
      child: CharadesApp(),
    ),
  );
}

class CharadesApp extends StatelessWidget {
  const CharadesApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Charades Master',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomeScreen(),
    );
  }
}


// TODO (Pedro Morais - 2026-04-08): Ideias
// Escolher um jogador já existente no highscore
// Load categories from json
// Exportar e importar highscore (json)
// Pausa durante o jogo (opções: retomar, home, reiniciar -> dá shuffle 
//  às palavras outra vez)
// Ecrã de resultados (jogo fast ou entre jogadores) mostra 
//  palavras acertadas e erradas
//   - Jogo fast: Botão de reiniciar ou ir para o home screen
//   - Jogo normal: Botão de próximo jogador / reiniciar 
//      e botão terminar / ir para o home screen
//   - Highscore permite ver em mais detalhe as palavras acertadas e 
//      erradas (organizadas por categoria)
// durante o jogo não bloquear o ecrã (ecrã sempre ativo)
// para jogo de multi categoria, também mostrar a categoria (por 
//  baixo da palavra), texo mais pequeno
// portrait e landscape: jogo sempre em landscape (avisa utilizador 
//  para meter em landscape); tudo o resto em portrait
// não permitir que palavras partam de linha (reduzir tamanho do texto)
// l10n
// tests
// multiple blocs?
// Refactor -> refactor services
// Category:
// - Has button to alternate between single and multi select (default single select)
// - Categories are cards

// Ver exemplo app GuessUp, Charades (telemóvel Bia)